export default {
    Success: { code: 200, message: "Success" },
    ServerError: { code: 400, message: "Something went wrong" },
    Unauthorized: { code: 401, message: "Unauthorized" },
    PaymentRequired: { code: 402, message: "Payment required" },
    Forbidden: { code: 403, message: "Forbidden" },
    NotFound: { code: 404, message: "Not Found" },
    MethodsNotAllowed: { code: 405, message: "Methods not allowed" },
    NotAcceptable: { code: 406, message: "Not acceptable" },
    ProxyAuthenticationRequired: { code: 407, message: "Proxy authentication required" },
    RequestTimeout: { code: 408, message: "Request Timeout" },
    Conflict: { code: 409, message: "Conflict" },
    InvalidCredentials: { code: 410, message: "Invalid Credentials" },
    EmailTaken: { code: 411, message: "Email taken" },
    UsernameTaken: { code: 412, message: "Username taken" },
    InvalidSymbols: { code: 413, message: "Invalid Symbols" },
    UsernameBanned: { code: 414, message: "Username banned" },
    InvalidToken: { code: 415, message: "Invalid token" },
    WrongCurrentPassword: { code: 416, message: "Wrong current password" },
    NoImage: { code: 417, message: "No image provided. Empty request" },
    InvalidFormat: { code: 418, message: "Invalid Format" },
    FileTooLarge: { code: 419, message: "File too large" },
    FileNotImage: { code: 420, message: "File not an image" },
    PasswordsCantMatch: { code: 421, message: "Current and new password matches"},
    InsufficientCredentials: { code: 422, message: "Insufficient Credentials" },
    PasswordsNoMatch: { code: 423, message: "Passwords don't match" },
}